/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import java.awt.Image;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelosDAO.AlbumCancion;
import modelosDAO.Cancion;
import modelosDAO.CancionDAO;
import utiles.Conexion;

/**
 *
 * @author igorr
 */
public class iAddCancion extends javax.swing.JFrame {

    Conexion miConexion = new Conexion();
    AlbumCancion miAlbumCancion = new AlbumCancion();
    CancionDAO miCancionDao = new CancionDAO();
    Cancion miCancion = new Cancion();
    DefaultTableModel modeloTabla = new DefaultTableModel();
    public int id;
    public String miImagen;
    private int id_seleccionado;

    /**
     * Creates new form iAddCancion
     */
    
   
    public iAddCancion(int _id, String _miImagen) {
        this.id = _id;
        this.miImagen = _miImagen;
        initComponents();
        dameTodoAlbum(id);
        Image img = new ImageIcon("src/img/"+miImagen).getImage();
        ImageIcon img2 = new ImageIcon(img.getScaledInstance(jLabelMiImagen.getWidth(), jLabelMiImagen.getHeight(), Image.SCALE_SMOOTH));

        jLabelMiImagen.setIcon(img2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        formnombreCancion = new javax.swing.JTextField();
        formDescripcionCancion = new javax.swing.JTextField();
        addCancion = new javax.swing.JButton();
        actualizar = new javax.swing.JButton();
        borrar = new javax.swing.JButton();
        jLabelMiImagen = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaAlbumCancion = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nombre: ");

        jLabel2.setText("Decripcion: ");

        addCancion.setText("Add Cancion");
        addCancion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCancionActionPerformed(evt);
            }
        });

        actualizar.setText("Actualizar");
        actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizarActionPerformed(evt);
            }
        });

        borrar.setText("Borrar");
        borrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelMiImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(formnombreCancion, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(formDescripcionCancion, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(borrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(addCancion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(actualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabelMiImagen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(222, 222, 222)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(addCancion, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                            .addComponent(formnombreCancion))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(formDescripcionCancion)
                            .addComponent(actualizar, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE))))
                .addGap(18, 18, 18)
                .addComponent(borrar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        tablaAlbumCancion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Numero de cancion", "Nombre Cancion", "Descripcion", "Grupo musical", "Album", "Año"
            }
        ));
        tablaAlbumCancion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaAlbumCancionMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaAlbumCancion);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 764, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void borrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrarActionPerformed
        borrarCancion();
        limpiarTabla();
        dameTodoAlbum(id);
    }//GEN-LAST:event_borrarActionPerformed

    private void addCancionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCancionActionPerformed
        addCancion();
        limpiarTabla();
        dameTodoAlbum(id);
    }//GEN-LAST:event_addCancionActionPerformed

    private void actualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizarActionPerformed
        actualizar();
        limpiarTabla();
        dameTodoAlbum(id);
    }//GEN-LAST:event_actualizarActionPerformed

    private void tablaAlbumCancionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaAlbumCancionMouseClicked
        int fila = tablaAlbumCancion.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(this, "Seleccina cancion por favor!!!");
        } else {
            id_seleccionado = Integer.parseInt(tablaAlbumCancion.getValueAt(fila, 0).toString());
            String nombre_cancion = tablaAlbumCancion.getValueAt(fila, 1).toString();
            String descripcion = tablaAlbumCancion.getValueAt(fila, 2).toString();
            String grupo_musical = tablaAlbumCancion.getValueAt(fila, 3).toString();
            String album = tablaAlbumCancion.getValueAt(fila, 4).toString();
            int anno = Integer.parseInt(tablaAlbumCancion.getValueAt(fila, 5).toString());

            formnombreCancion.setText(nombre_cancion);
            formDescripcionCancion.setText(descripcion);
        }
    }//GEN-LAST:event_tablaAlbumCancionMouseClicked

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton actualizar;
    private javax.swing.JButton addCancion;
    private javax.swing.JButton borrar;
    private javax.swing.JTextField formDescripcionCancion;
    private javax.swing.JTextField formnombreCancion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelMiImagen;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaAlbumCancion;
    // End of variables declaration//GEN-END:variables

    private void dameTodoAlbum(int id) {
        List<AlbumCancion> miListaAlbumCancion = miCancionDao.dameTodoPorId(id);
        modeloTabla = (DefaultTableModel) tablaAlbumCancion.getModel();
        Object[] o = new Object[6];
        for (int i = 0; i < miListaAlbumCancion.size(); i++) {
            o[0] = miListaAlbumCancion.get(i).getCancion_id();
            o[1] = miListaAlbumCancion.get(i).getNombre_cancion();
            o[2] = miListaAlbumCancion.get(i).getDescripcion();
            o[3] = miListaAlbumCancion.get(i).getGrupo_musical();
            o[4] = miListaAlbumCancion.get(i).getNombre();
            o[5] = miListaAlbumCancion.get(i).getAnno();
            modeloTabla.addRow(o);
        }
        tablaAlbumCancion.setModel(modeloTabla);

    }

    void limpiarTabla() {
        for (int i = 0; i < modeloTabla.getRowCount(); i++) {
            modeloTabla.removeRow(i);
            i = i - 1;
        }
    }

    private void borrarCancion() {
        int fila = tablaAlbumCancion.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(this, "No has seleccionado ninguna cancion, para borrar!!!");
        } else {
            id_seleccionado = Integer.parseInt(tablaAlbumCancion.getValueAt(fila, 0).toString());
            miCancionDao.eliminar(id_seleccionado);
            String nombre_cancion = tablaAlbumCancion.getValueAt(fila, 1).toString();
            String descripcion = tablaAlbumCancion.getValueAt(fila, 2).toString();
            String grupo_musical = tablaAlbumCancion.getValueAt(fila, 3).toString();
            String album = tablaAlbumCancion.getValueAt(fila, 4).toString();
            int anno = Integer.parseInt(tablaAlbumCancion.getValueAt(fila, 5).toString());
            limpiar();

        }

    }

    private void limpiar() {
        formnombreCancion.setText("");
        formDescripcionCancion.setText("");
    }

    private void addCancion() {
        String nombre_cancion = formnombreCancion.getText();
        String descripcion = formDescripcionCancion.getText();

        Object[] o = new Object[3];
        o[0] = nombre_cancion;
        o[1] = descripcion;
        o[2] = id;

        miCancionDao.guardar(o);
        limpiar();

    }

    private void actualizar() {
        int fila = tablaAlbumCancion.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(this, "para poder modificar una cancion deberias "
                    + "seleccionarla previamente!!!!");
        } else {
            String nombre_cancion = formnombreCancion.getText();
            String descripcion = formDescripcionCancion.getText();
            Object[] o = new Object[3];
            o[0] = nombre_cancion;
            o[1] = descripcion;
            o[2] = id_seleccionado;
            miCancionDao.actuaizar(o);
        }

        limpiar();

    }

}
